/*
 
 xTalk Engine Tests: Handler Parsing: Conditions
 xtalk_test_exprs.c
 
 CinsImp
 Copyright (c) 2010-2013 Joshua Hawcroft
 <www.joshhawcroft.com/CinsImp/>
 
 Unit tests for handler parsing of conditions
 
 *************************************************************************************************
 */

#include "xtalk_internal.h"


#if XTALK_TESTS



struct XTETestParserCase const _TEST_IFS_ERROR[] = {
    {
        "on mouseUp\n"
        "  else\n"
        "end mouseUp"
        ,
        "\"else\" not allowed here."
    },
    {
        "on mouseUp\n"
        "  repeat 3\n"
        "    else\n"
        "  end repeat\n"
        "end mouseUp"
        ,
        "\"else\" not allowed here."
    },
    {
        "on mouseUp\n"
        "  if greg <> josh\n"
        "  then\n"
        "  else\n"
        "  end repeat\n"
        "end mouseUp"
        ,
        "Expected \"end if\" but found \"end repeat\"."
    },
    {
        "on mouseUp\n"
        "  if greg <> josh\n"
        "  then\n"
        "  else\n"
        "  end robert\n"
        "end mouseUp"
        ,
        "Expected \"end if\" but found \"end robert\"."
    },
    {
        "on mouseUp\n"
        "  if greg <> josh\n"
        "  then\n"
        "  else\n"
        "  end\n"
        "end mouseUp"
        ,
        "Expected \"end if\" but found end of line."
    },
    {
        "on mouseUp\n"
        "  if greg <> josh\n"
        "  then\n"
        "  else\n"
        "  end if if\n"
        "end mouseUp"
        ,
        "Expected end of line after \"end if\"."
    },
    {
        "on mouseUp\n"
        "  if \n"
        "  then\n"
        "  else\n"
        "  end if\n"
        "end mouseUp"
        ,
        "Expected true or false expression here."
    },
    {
        "on mouseUp\n"
        "  if  then\n"
        "  end if\n"
        "end mouseUp"
        ,
        "Expected true or false expression here."
    },
    {
        "on mouseUp\n"
        "  if josh = bob\n"
        "  repeat\n"
        "  end if\n"
        "end mouseUp"
        ,
        "Expecting \"then\" here."
    },
    {
        "on mouseUp\n"
        "  if josh = bob\n"
        "  end if\n"
        "end mouseUp"
        ,
        "Expecting \"then\" here."
    },
    {
        "on mouseUp\n"
        "  if josh = bob\n"
        "  5\n"
        "end mouseUp"
        ,
        "Expecting \"then\" here."
    },
    {//12
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else if cookies = 1 then put \"only 1 cookie!\" else if cookies = 4 then bob\n"
        "end mouseUp"
        ,
        "\"else\" cannot follow \"else if\" on the same line."
    },
    {
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else if cookies = 1\n"
        "  then put \"only 1 cookie!\" else if cookies = 4 then bob\n"
        "end mouseUp"
        ,
        "\"else if\" cannot follow \"then\" on the same line."
    },
    {
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else\n"
        "    put \"only 1 cookie!\"\n"
        "  else\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"else\"."
    },
    {
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else if cookies = 1 then else if cookies = 4 then bob\n"
        "end mouseUp"
        ,
        "Expected some statement but found \"else\"."
    },
    {
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else if cookies = 1 then beep \n"
        "  else\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"if\"."
    },
    {
        "on mouseUp\n"
        "  if boots = 1 then\n"
        "    if cookies = 2 then put \"2 cookies\"\n"
        "    else\n"
        "  end if\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"if\"."
    },
    {
        "on mouseUp\n"
        "  repeat\n"
        "    if cookies = 2 then put \"2 cookies\"\n"
        "    else\n"
        "    beep 8\n"
        "  end repeat\n"
        "end mouseUp"
        ,
        "Expected \"end if\" but found \"end repeat\"."
    },
    {
        "on mouseUp\n"
        "  repeat\n"
        "    if cookies = 2 then put \"2 cookies\"\n"
        "    else\n"
        "  end repeat\n"
        "end mouseUp"
        ,
        "Expected \"end if\" but found \"end repeat\"."
    },
    {
        "on mouseUp\n"
        "  if name = \"Henry Cavill\"\n"
        "  then put \"You're hot!\"\n"
        "  else\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"if\"."
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else\n"
        "      put \"Hello Josh.\"\n"
        "    end if\n"
        "  else if name = \"Andrew\" then\n"
        "    put \"You're quite good looking.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"if\"."
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else\n"
        "      put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\" then\n"
        "    put \"You're quite good looking.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "Expected \"end if\" after \"else\"."
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\" then\n"
        "  then put \"Hi Andrew\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "Expected command name but found \"then\"."
    },
    NULL
};



struct XTETestParserCase const _TEST_IFS_OK[] = {
    {
        "on mouseUp\n"
        "  if josh <> greg then\n"
        "  end if -- end of condition\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR not equal\n"
        "            WORD josh (FLAGS=$0)\n"
        "            WORD greg (FLAGS=$0)\n"
        "      LIST ()\n"
    },
    {
        "on mouseUp\n"
        "  if cookies = 2 then\n"
        "    put \"2 cookies\"\n"
        "  else if cookies = 1 then put \"only 1 cookie!\"\n"
        "  else if cookies = 4 then beep\n"
        "  else put \"No idea about cookies\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD cookies (FLAGS=$0)\n"
        "            INTEGER 2\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"2 cookies\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD cookies (FLAGS=$0)\n"
        "            INTEGER 1\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"only 1 cookie!\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD cookies (FLAGS=$0)\n"
        "            INTEGER 4\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (beep)\n"
        "         PARAMS:\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"No idea about cookies\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\" then exit mouseUp\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         EXIT handler (return)\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\" then put \"Hello Josh.\" else put \"Hi there.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi there.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\" \n"
        "  then put \"Hello Josh.\" \n"
        "  else put \"Hi there.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi there.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    put \"Hello Josh.\"\n"
        "  else put \"Hi there.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi there.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    put \"Hello Josh.\"\n"
        "  else\n"
        "    put \"Hi there.\"\n"
        "  end if\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi there.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\" then\n"
        "    put \"Hello Josh.\"\n"
        "  else\n"
        "    put \"Hi there.\"\n"
        "  end if\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi there.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\"\n"
        "  then put \"You're quite good looking.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\"\n"
        "  then put \"You're quite good looking.\"\n"
        "  else if name = \"Henry\"\n"
        "  then put \"Man you're hot!\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Henry\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Man you're hot!\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\"\n"
        "  then put \"You're quite good looking.\"\n"
        "  else if name = \"Henry\"\n"
        "  then put \"Man you're hot!\"\n"
        "  else put \"I don't know you.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Henry\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Man you're hot!\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"I don't know you.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\" then\n"
        "  put \"You're quite good looking.\"\n"
        "  else if name = \"Henry\" then put \"Man you're hot!\"\n"
        "  else put \"I don't know you.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hello Josh.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Henry\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Man you're hot!\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"I don't know you.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else\n"
        "      put \"Hello Josh.\"\n"
        "    end if\n"
        "  else if name = \"Andrew\" then\n"
        "    put \"You're quite good looking.\"\n"
        "  else if name = \"Henry\" then put \"Man you're hot!\"\n"
        "  else put \"I don't know you.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         CONDITION\n"
        "            EXPRESSION ()\n"
        "               WORD isJoshBirthday (FLAGS=$0)\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Happy Birthday Josh!\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Hello Josh.\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Henry\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Man you're hot!\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"I don't know you.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\" then\n"
        "    put \"You're quite good looking.\"\n"
        "  else if name = \"Henry\" then put \"Man you're hot!\"\n"
        "  else put \"I don't know you.\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         CONDITION\n"
        "            EXPRESSION ()\n"
        "               WORD isJoshBirthday (FLAGS=$0)\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Happy Birthday Josh!\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Hello Josh.\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"You're quite good looking.\"\n"
        "            NULL\n"
        "            NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Henry\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Man you're hot!\"\n"
        "            NULL\n"
        "            NULL\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"I don't know you.\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    {
        "on mouseUp\n"
        "  if name = \"Josh\"\n"
        "  then\n"
        "    if isJoshBirthday then\n"
        "      put \"Happy Birthday Josh!\"\n"
        "    else put \"Hello Josh.\"\n"
        "  else if name = \"Andrew\"\n"
        "  then put \"Hi Andrew\"\n"
        "  beep 2\n"
        "end mouseUp"
        ,
        "HANDLER C \"mouseUp\"\n"
        "   PARAM-NAMES\n"
        "   CONDITION\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Josh\"\n"
        "      LIST ()\n"
        "         CONDITION\n"
        "            EXPRESSION ()\n"
        "               WORD isJoshBirthday (FLAGS=$0)\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Happy Birthday Josh!\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "            LIST ()\n"
        "               COMMAND fPTR=$0 (put)\n"
        "               PARAMS:\n"
        "                  EXPRESSION (source)\n"
        "                     STRING \"Hello Josh.\"\n"
        "                  NULL\n"
        "                  NULL\n"
        "      EXPRESSION ()\n"
        "         OPERATOR equal\n"
        "            WORD name (FLAGS=$0)\n"
        "            STRING \"Andrew\"\n"
        "      LIST ()\n"
        "         COMMAND fPTR=$0 (put)\n"
        "         PARAMS:\n"
        "            EXPRESSION (source)\n"
        "               STRING \"Hi Andrew\"\n"
        "            NULL\n"
        "            NULL\n"
        "   COMMAND fPTR=$0 (beep)\n"
        "   PARAMS:\n"
        "      EXPRESSION ()\n"
        "         INTEGER 2\n"
    },
    NULL
};



#endif


